workflow: eap
gcs_prefix: "eap-clean"
args:
  modules:
  - eap
  - top-components
  - node-selection
  top-n: 500
  selection-limit: 300
  compute-completeness: true
  compute-gradient-at: clean
  save-to-gcp: true
