workflow: eap
gcs_prefix: "eap-corrupted"
args:
  modules:
  - top-components
  - node-selection
  top-n: 500
  selection-limit: 300
  compute-completeness: true
  compue-gradient-at: corrupted
  save-to-gcp: true
